language: cpp

sudo: required

cache: ccache

matrix:
  include:
    # Ubuntu 14.04 + GCC 4.8 + Qt 5.2 + Doxygen Generation (all packages from official Ubuntu repositories)
    - os: linux
      dist: trusty
      compiler: gcc
      env: BUILD_DOXYGEN=true QT_BASE="trusty"
    # Ubuntu 14.04 + Clang + Latest Qt from beineri PPA (https://launchpad.net/~beineri)
    - os: linux
      dist: trusty
      compiler: clang
      env: BUILD_DOXYGEN=false QT_BASE="qt57" QT_PPA="ppa:beineri/opt-qt57-trusty"
    # OS X + GCC
    - os: osx
      compiler: gcc
      env: BUILD_DOXYGEN=false
    # OS X + Clang
    - os: osx
      compiler: clang
      env: BUILD_DOXYGEN=false
  fast_finish: true

env:
  global:
    - secure: "QW5QTwmLqovoDDrwVGXIOh+jd+ArwWSAy2P1U5xDW3C7oE5lgHQH3bqStEv63aOxvpN9cgqjroXQfCpKz+nNO7Rur0MY7UXCUxk0VizCOn4CUg7K7XeHTJEvzGRke2j7QUNigE5GTu9ABAeSN/AfHAtWVCFrecMINqTLWWC3pB/dTalCX6NoQb2f1z2nbdHa+suT8NoUo14eXrQfIZ9xnVrQ7NYuMXyb5A0akyQSq1oNb+5yj1o1wdmaNaCkalGyN2Oj/aD8urSU65sahwOQlhCwnxKDVuFqhcgV4ux6k42B7VJuVhxC2j71vCS4Kfka00/WVTNJXmdDxB873o+GqGVElvc5QeimQX34Zw2b+u77teZku4y33wm1wazh6mGh13/4EzA325rqjaxlge4EE5Bzq5qIhmaLspwob1EQD/waEhSDptNCK5bgP+OBtGi1f8vAnjlhh/3U10oWtAV1faV88zx9q0mWb4yYyoLP6D3ViglL62E9hKpwL2uXpGeb6yTCHfcpNMqkwFwYFt+Dj5vJ9RG4kmlsg4oXUn47zCOwj2ynOR24q9xgR+7d2Zj2vzfE/PPWbn8UGO6VcZtn6CpBUn6kMpfh5BcvBA06aFh/neW9WxAe9W7X6w1n1whpkTE2ro3iJDlVDiY+QTlCuZJg6EvLmKuHMf6oKM5WNC0="

before_install:
  - | 
    if [ -n "$QT_PPA" ]
    then
      sudo add-apt-repository "${QT_PPA}" -y && sudo apt-get update -qq
    fi

install:
  - |
    if [ "${TRAVIS_OS_NAME}" = "linux" ]
    then
      sudo apt-get install -qq libglu1-mesa-dev
      if [ "$QT_BASE" = "trusty" ]; then sudo apt-get install -qq qt5-default qttools5-dev-tools; fi
      if [ -n "$QT_PPA" ]; then sudo apt-get install -qq "${QT_BASE}base" "${QT_BASE}tools"; source "/opt/${QT_BASE}/bin/${QT_BASE}-env.sh"; fi
      if [ "$BUILD_DOXYGEN" = "true" ]; then sudo apt-get install -qq doxygen graphviz; fi
    elif [ "${TRAVIS_OS_NAME}" = "osx" ]
    then 
      brew update && brew install qt5 && brew link --force qt5
    fi

script:
  - mkdir build && cd build && qmake ../librepcb.pro -r "QMAKE_CXX=$CXX" "QMAKE_CC=$CC" && make -j8 && cd ../   # build librepcb
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then ./build/generated/unix/tests; fi                                 # run all unit tests (linux)
  - if [ "${TRAVIS_OS_NAME}" = "osx" ];   then ./build/generated/mac/tests; fi                                  # run all unit tests (mac)

# run doxygen and upload the html output to github (gh-pages of LibrePCB-Doxygen)
after_success:
  - |
    if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${BUILD_DOXYGEN}" = "true" ]
    then 
      BRANCH_NAME=$(echo ${TRAVIS_BRANCH} | sed -e 's/[^A-Za-z0-9._-]/_/g')
      cd ./dev/doxygen && doxygen Doxyfile
      git clone -b gh-pages $DOXYGEN_REPOSITORY && cd LibrePCB-Doxygen
      mkdir -p $BRANCH_NAME && rm -rf $BRANCH_NAME/* && cp -rf ../output/html/* ./$BRANCH_NAME
      git config user.name "LibrePCB-Builder" && git config user.email "builder@librepcb.org"
      git add -A > /dev/null && git commit -m "updated doxygen documentation of branch $BRANCH_NAME" && git push origin gh-pages
    fi
