version: 0.1.{build}-{branch}
os: Windows Server 2012
configuration: Debug
build: off
test: off
deploy: off

environment:
  global:
    MINGW: C:\Qt\Tools\mingw492_32
  matrix:
    - QTDIR: C:\Qt\5.5\mingw492_32

init:
  - git config --global core.autocrlf input
  - set PATH=%QTDIR%\bin;%MINGW%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - qmake ..\librepcb.pro -r
  - mingw32-make -j 4
  - .\generated\windows\qztest.exe # run quazip unit tests
  - .\generated\windows\tests.exe # run librepcb unit tests
  - cd ..\

