version: '{build}'
os: Windows Server 2012
configuration: Debug
build: off
test: off
deploy: off

environment:
  global:
    MINGW: C:\Qt\Tools\mingw530_32
  matrix:
    - QTDIR: C:\Qt\5.7\mingw53_32

init:
  - set PATH=%QTDIR%\bin;%MINGW%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%

install:
  - git submodule update --init --recursive

build_script:
  - mkdir build
  - cd build
  - qmake -r ..\librepcb.pro
  - mingw32-make -j 4
  - .\generated\windows\qztest.exe # run quazip unit tests
  - .\generated\windows\tests.exe  # run librepcb unit tests
